"""
Discord Bot - Moderation, Music & Welcome
==========================================
Bot Discord lengkap dengan fitur moderation, music player, dan welcome member.

Author: Generated by Antigravity AI
"""

import os
import discord
from discord.ext import commands
import asyncio

# Load configuration - PRIORITAS: Environment Variables (WispByte) > config.py
# Di cloud deployment, environment variables harus diutamakan
BOT_TOKEN = os.environ.get('DISCORD_BOT_TOKEN', '')
PREFIX = os.environ.get('PREFIX', '!')

# Fallback ke config.py HANYA jika environment variables kosong (untuk local development)
_config_module = None
if not BOT_TOKEN:
    try:
        import config as _config_module
        BOT_TOKEN = _config_module.BOT_TOKEN
        PREFIX = _config_module.PREFIX if hasattr(_config_module, 'PREFIX') else '!'
    except ImportError:
        pass

# Default jika masih kosong
if not BOT_TOKEN:
    BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"

# Helper function untuk mendapatkan config values
def get_colors():
    """Get COLORS config with fallback."""
    if _config_module and hasattr(_config_module, 'COLORS'):
        return _config_module.COLORS
    # Default colors
    return {
        "success": 0x2ECC71,
        "error": 0xE74C3C,
        "warning": 0xF39C12,
        "info": 0x3498DB,
        "music": 0x9B59B6,
        "welcome": 0x1ABC9C,
        "leveling": 0xFFD700,
        "chatbot": 0x00D9FF,
    }

COLORS = get_colors()

# Import dashboard module
try:
    from dashboard.backend import database as db
    HAS_DATABASE = True
    # Initialize database tables
    db.init_db()
except ImportError:
    HAS_DATABASE = False
    db = None


async def async_get_prefix(bot, message) -> str:
    """Get prefix dynamically based on guild."""
    if message.guild:
        guild_id = message.guild.id
        if HAS_DATABASE and db:
            try:
                settings = db.get_guild_settings(guild_id)
                if settings and settings.get('command_prefix'):
                    return settings['command_prefix']
            except Exception as e:
                print(f"Error getting prefix from DB: {e}")
    return PREFIX


class DiscordBot(commands.Bot):
    """Main Discord Bot class."""

    def __init__(self):
        # Define intents
        intents = discord.Intents.default()
        intents.message_content = True  # Untuk baca message content
        intents.members = True  # Untuk welcome/goodbye events
        intents.voice_states = True  # Untuk music player
        intents.guilds = True

        super().__init__(
            command_prefix=async_get_prefix,  # Dynamic prefix from database
            intents=intents,
            help_command=CustomHelpCommand(),
            case_insensitive=True,  # Commands tidak case-sensitive
        )

    async def setup_hook(self):
        """Load all cogs saat bot startup."""
        cogs = [
            "cogs.moderation",
            "cogs.music",
            "cogs.welcome",
            "cogs.leveling",
            "cogs.chatbot",
        ]

        for cog in cogs:
            try:
                await self.load_extension(cog)
                print(f"[OK] Loaded: {cog}")
            except Exception as e:
                print(f"[ERROR] Failed to load {cog}: {e}")

    async def on_ready(self):
        """Event handler saat bot ready."""
        print("=" * 50)
        print(f"[BOT] Bot is ready!")
        print(f"[BOT] Logged in as: {self.user.name}")
        print(f"[BOT] Bot ID: {self.user.id}")
        print(f"[BOT] Connected to {len(self.guilds)} server(s)")
        print(f"[BOT] Prefix: {PREFIX}")
        print("=" * 50)

        # Set bot status
        await self.change_presence(
            activity=discord.Activity(
                type=discord.ActivityType.listening,
                name=f"{PREFIX}help | Music, Leveling & AI Chatbot"
            ),
            status=discord.Status.online
        )

    async def on_command_error(self, ctx: commands.Context, error):
        """Global error handler."""
        if hasattr(ctx.command, 'on_error'):
            return

        cog = ctx.cog
        if cog and hasattr(cog, '_get_overridden_method'):
            if cog._get_overridden_method(cog.cog_command_error) is not None:
                return

        if isinstance(error, commands.CommandNotFound):
            # Ignore command not found
            return
        elif isinstance(error, commands.CommandOnCooldown):
            embed = discord.Embed(
                title="⏱️ Cooldown",
                description=f"Command sedang cooldown! Coba lagi dalam **{error.retry_after:.1f}** detik.",
                color=COLORS["warning"]
            )
            await ctx.send(embed=embed, delete_after=5)
        elif isinstance(error, commands.MissingPermissions):
            embed = discord.Embed(
                title="❌ Missing Permissions",
                description="Kamu tidak memiliki permission untuk menggunakan command ini!",
                color=COLORS["error"]
            )
            await ctx.send(embed=embed)
        elif isinstance(error, commands.BotMissingPermissions):
            embed = discord.Embed(
                title="❌ Bot Missing Permissions",
                description=f"Bot tidak memiliki permission yang diperlukan: `{', '.join(error.missing_permissions)}`",
                color=COLORS["error"]
            )
            await ctx.send(embed=embed)
        elif isinstance(error, commands.NoPrivateMessage):
            embed = discord.Embed(
                title="❌ Server Only",
                description="Command ini hanya bisa digunakan di server!",
                color=COLORS["error"]
            )
            await ctx.send(embed=embed)
        else:
            print(f"Unhandled error: {error}")


class CustomHelpCommand(commands.HelpCommand):
    """Custom help command dengan embed yang cantik."""

    def __init__(self):
        super().__init__()

    async def send_bot_help(self, mapping):
        """Send help untuk semua commands."""
        embed = discord.Embed(
            title="📚 Bot Help",
            description=(
                f"Prefix: `{PREFIX}`\n"
                f"Gunakan `{PREFIX}help <command>` untuk info lebih lanjut.\n\n"
            ),
            color=COLORS["info"]
        )

        for cog, commands_list in mapping.items():
            filtered = await self.filter_commands(commands_list, sort=True)
            if filtered:
                cog_name = getattr(cog, "qualified_name", "Other")
                command_names = [f"`{c.name}`" for c in filtered]
                if command_names:
                    embed.add_field(
                        name=f"🔹 {cog_name}",
                        value=", ".join(command_names),
                        inline=False
                    )

        embed.set_footer(text=f"Total {len([c for c in self.context.bot.commands])} commands")

        channel = self.get_destination()
        await channel.send(embed=embed)

    async def send_command_help(self, command):
        """Send help untuk command spesifik."""
        embed = discord.Embed(
            title=f"📖 Command: {command.name}",
            description=command.help or "Tidak ada deskripsi.",
            color=COLORS["info"]
        )

        # Usage
        signature = self.get_command_signature(command)
        embed.add_field(name="Usage", value=f"`{signature}`", inline=False)

        # Aliases
        if command.aliases:
            embed.add_field(
                name="Aliases",
                value=", ".join([f"`{a}`" for a in command.aliases]),
                inline=False
            )

        channel = self.get_destination()
        await channel.send(embed=embed)

    async def send_cog_help(self, cog):
        """Send help untuk cog/category."""
        embed = discord.Embed(
            title=f"📂 Category: {cog.qualified_name}",
            description=cog.description or "Tidak ada deskripsi.",
            color=COLORS["info"]
        )

        filtered = await self.filter_commands(cog.get_commands(), sort=True)
        if filtered:
            for command in filtered:
                embed.add_field(
                    name=command.name,
                    value=command.help or "Tidak ada deskripsi.",
                    inline=False
                )

        channel = self.get_destination()
        await channel.send(embed=embed)

    async def send_error_message(self, error):
        """Send error message."""
        embed = discord.Embed(
            title="❌ Error",
            description=error,
            color=COLORS["error"]
        )

        channel = self.get_destination()
        await channel.send(embed=embed)


async def main():
    """Main function untuk menjalankan bot."""
    bot = DiscordBot()

    # Check token
    if not BOT_TOKEN or BOT_TOKEN == "YOUR_BOT_TOKEN_HERE":
        print("=" * 50)
        print("[ERROR] Bot token belum dikonfigurasi!")
        print("")
        print("Set DISCORD_BOT_TOKEN environment variable atau")
        print("edit file config.py dan isi BOT_TOKEN")
        print("dengan token bot dari Discord Developer Portal.")
        print("=" * 50)
        return

    try:
        await bot.start(BOT_TOKEN)
    except discord.LoginFailure:
        print("[ERROR] Token tidak valid! Periksa kembali token bot Anda.")
    except Exception as e:
        print(f"[ERROR] Error: {e}")


if __name__ == "__main__":
    asyncio.run(main())
